# Generated by Django 4.0.6 on 2022-07-19 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hallBooking_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfrenceHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=200)),
                ('max_occupancy', models.IntegerField()),
                ('booking_limit', models.IntegerField()),
                ('isactive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HallBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('participantcount', models.IntegerField()),
                ('purpose', models.CharField(max_length=255)),
                ('remarks', models.JSONField(default=hallBooking_app.models.HallBookings.json_default1)),
                ('response', models.JSONField(default=hallBooking_app.models.HallBookings.json_default1)),
                ('responseTime', models.JSONField(default=hallBooking_app.models.HallBookings.json_default1)),
                ('isEditable', models.BooleanField(default=False)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallBooking_app.confrencehall')),
                ('submittedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfrenceHallImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hall/images')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hallBooking_app.confrencehall')),
            ],
        ),
    ]
