# Generated by Django 4.0.6 on 2022-07-20 19:40

from django.db import migrations, models
import hallBooking_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hallBooking_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallbookings',
            name='isEditable',
            field=models.JSONField(default=hallBooking_app.models.HallBookings.json_default1),
        ),
    ]
