# Generated by Django 4.0.6 on 2022-07-21 12:36

from django.db import migrations, models
import hallBooking_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('hallBooking_app', '0002_alter_hallbookings_iseditable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallbookings',
            name='response',
            field=models.JSONField(default=hallBooking_app.models.HallBookings.json_default2),
        ),
    ]
